//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Messages.CommonMessages", typeof(CommonMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string BadRequestKey {
            get {
                return ResourceManager.GetString("BadRequestKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CompanyGuid.
        /// </summary>
        public static string CompanyGuid_Invalid {
            get {
                return ResourceManager.GetString("CompanyGuid_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact your provider with the error id ({0}).
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension is invalid - Only upload jpg/jpeg/png file.
        /// </summary>
        public static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request Data.
        /// </summary>
        public static string InvalidRequestData {
            get {
                return ResourceManager.GetString("InvalidRequestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewUser.
        /// </summary>
        public static string NewUser_Message {
            get {
                return ResourceManager.GetString("NewUser_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report not available. Please contact Verimoto Support..
        /// </summary>
        public static string Report_NotAvailable {
            get {
                return ResourceManager.GetString("Report_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this resource..
        /// </summary>
        public static string ResourceAccessPermission_Invalid {
            get {
                return ResourceManager.GetString("ResourceAccessPermission_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success_Message {
            get {
                return ResourceManager.GetString("Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one admin user should be present.
        /// </summary>
        public static string ValidateUser_Error_IsAdminRoleMandatory {
            get {
                return ResourceManager.GetString("ValidateUser_Error_IsAdminRoleMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one billing responsible user should be present in users list.
        /// </summary>
        public static string ValidateUser_Error_IsBillingResponsibleRoleMandatory {
            get {
                return ResourceManager.GetString("ValidateUser_Error_IsBillingResponsibleRoleMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one primary contact user should be present in users list.
        /// </summary>
        public static string ValidateUser_Error_IsPrimaryContactRoleMandatory {
            get {
                return ResourceManager.GetString("ValidateUser_Error_IsPrimaryContactRoleMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be only one billing resposible user.
        /// </summary>
        public static string ValidateUser_Error_OnlyOneBillingResponsibleRole {
            get {
                return ResourceManager.GetString("ValidateUser_Error_OnlyOneBillingResponsibleRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be only one primary contact user.
        /// </summary>
        public static string ValidateUser_Error_OnlyOnePrimaryContactRole {
            get {
                return ResourceManager.GetString("ValidateUser_Error_OnlyOnePrimaryContactRole", resourceCulture);
            }
        }
    }
}
