//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Messages.ConfigMessages", typeof(ConfigMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetsWorkWith List required.
        /// </summary>
        public static string AssetsWorkWith_Error_Required {
            get {
                return ResourceManager.GetString("AssetsWorkWith_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker Companies not found.
        /// </summary>
        public static string BrokerCompanies_Error_NotFound {
            get {
                return ResourceManager.GetString("BrokerCompanies_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Broker Company.
        /// </summary>
        public static string BrokerCompany_Invalid {
            get {
                return ResourceManager.GetString("BrokerCompany_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker Users not found.
        /// </summary>
        public static string BrokerUsers_Error_NotFound {
            get {
                return ResourceManager.GetString("BrokerUsers_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrokerUsers List required.
        /// </summary>
        public static string BrokerUsersList_Error_Required {
            get {
                return ResourceManager.GetString("BrokerUsersList_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Details required.
        /// </summary>
        public static string CardDetails_Required {
            get {
                return ResourceManager.GetString("CardDetails_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies not found.
        /// </summary>
        public static string Companies_NotFound {
            get {
                return ResourceManager.GetString("Companies_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name already exists..
        /// </summary>
        public static string Company_Error_AlreadyExists {
            get {
                return ResourceManager.GetString("Company_Error_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid company.
        /// </summary>
        public static string Company_Invalid {
            get {
                return ResourceManager.GetString("Company_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyContacts required.
        /// </summary>
        public static string CompanyContacts_Error_Required {
            get {
                return ResourceManager.GetString("CompanyContacts_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Guid Required.
        /// </summary>
        public static string CompanyGuid_Required {
            get {
                return ResourceManager.GetString("CompanyGuid_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected company visibility already exist.
        /// </summary>
        public static string CompanyVisibility_Error_SameVisibility {
            get {
                return ResourceManager.GetString("CompanyVisibility_Error_SameVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is required.
        /// </summary>
        public static string GetCreditCard_Error_CardNumber {
            get {
                return ResourceManager.GetString("GetCreditCard_Error_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid lender.
        /// </summary>
        public static string Lender_Invalid {
            get {
                return ResourceManager.GetString("Lender_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Lender Company.
        /// </summary>
        public static string LenderCompany_Invalid {
            get {
                return ResourceManager.GetString("LenderCompany_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LendersWorkWith List required.
        /// </summary>
        public static string LendersWorkWith_Error_Required {
            get {
                return ResourceManager.GetString("LendersWorkWith_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewCompanyDetails required.
        /// </summary>
        public static string NewCompanyDetails_Error_Details {
            get {
                return ResourceManager.GetString("NewCompanyDetails_Error_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Card Details.
        /// </summary>
        public static string PaymentDetails_Error_InvalidCardDetails {
            get {
                return ResourceManager.GetString("PaymentDetails_Error_InvalidCardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Card Number.
        /// </summary>
        public static string PaymentDetails_Error_InvalidCardNumber {
            get {
                return ResourceManager.GetString("PaymentDetails_Error_InvalidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method is required.
        /// </summary>
        public static string PaymentMethods_Error_Required {
            get {
                return ResourceManager.GetString("PaymentMethods_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PlanGuid.
        /// </summary>
        public static string PlanGuid_Invalid {
            get {
                return ResourceManager.GetString("PlanGuid_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid State Details.
        /// </summary>
        public static string StateDetails_Invalid {
            get {
                return ResourceManager.GetString("StateDetails_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template not exists. Please verify template guid.
        /// </summary>
        public static string TemplatePlans_Error_TemplateNotExists {
            get {
                return ResourceManager.GetString("TemplatePlans_Error_TemplateNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        public static string User_Invalid {
            get {
                return ResourceManager.GetString("User_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users not found.
        /// </summary>
        public static string Users_NotFound {
            get {
                return ResourceManager.GetString("Users_NotFound", resourceCulture);
            }
        }
    }
}
