//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Messages.CoreMessages", typeof(CoreMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities not found.
        /// </summary>
        public static string Activities_NotFound {
            get {
                return ResourceManager.GetString("Activities_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection created successfully.
        /// </summary>
        public static string Application_Created {
            get {
                return ResourceManager.GetString("Application_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid WebHook Id.
        /// </summary>
        public static string B2BWebHook_Error_InvalidId {
            get {
                return ResourceManager.GetString("B2BWebHook_Error_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebHooks not available.
        /// </summary>
        public static string B2BWebHook_Error_WebHooksNotAvailable {
            get {
                return ResourceManager.GetString("B2BWebHook_Error_WebHooksNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyGuid is required.
        /// </summary>
        public static string CompanyGuid_Required {
            get {
                return ResourceManager.GetString("CompanyGuid_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name already exists..
        /// </summary>
        public static string CompanyName_Exists {
            get {
                return ResourceManager.GetString("CompanyName_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVS is Up &amp; Accepted..
        /// </summary>
        public static string DVSCheck_Accepted_Msg {
            get {
                return ResourceManager.GetString("DVSCheck_Accepted_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVS is down. Please try again later..
        /// </summary>
        public static string DVSCheck_Error_PingFailed {
            get {
                return ResourceManager.GetString("DVSCheck_Error_PingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVS is Up &amp; Rejected..
        /// </summary>
        public static string DVSCheck_Rejected_Msg {
            get {
                return ResourceManager.GetString("DVSCheck_Rejected_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Logs not found.
        /// </summary>
        public static string EditInspection_ActivityLogs_NotFound {
            get {
                return ResourceManager.GetString("EditInspection_ActivityLogs_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid inspection id / image id.
        /// </summary>
        public static string EditInspection_InspectionProgress_Error_InvalidInspectionIdOrImageId {
            get {
                return ResourceManager.GetString("EditInspection_InspectionProgress_Error_InvalidInspectionIdOrImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no pending documents for this inspection. Please check document status..
        /// </summary>
        public static string EditInspection_Reminder_Error_NoPendingDocs {
            get {
                return ResourceManager.GetString("EditInspection_Reminder_Error_NoPendingDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no rejected documents for this inspection. Please check document status..
        /// </summary>
        public static string EditInspection_Reminder_Error_NoRejectedDocs {
            get {
                return ResourceManager.GetString("EditInspection_Reminder_Error_NoRejectedDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot Edit this inspection now. Current Status is {0}.
        /// </summary>
        public static string EditInspection_Update_Validate_ApplicationStatus {
            get {
                return ResourceManager.GetString("EditInspection_Update_Validate_ApplicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Id and Image Id Required.
        /// </summary>
        public static string GetImageData_Error_InspectionId_ImageId {
            get {
                return ResourceManager.GetString("GetImageData_Error_InspectionId_ImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Id required.
        /// </summary>
        public static string ImageId_Error_Required {
            get {
                return ResourceManager.GetString("ImageId_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access this inspection.
        /// </summary>
        public static string Inspection_InvalidPermissionAccess {
            get {
                return ResourceManager.GetString("Inspection_InvalidPermissionAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InspectionGuid required.
        /// </summary>
        public static string InspectionGuid_Error_NotFound {
            get {
                return ResourceManager.GetString("InspectionGuid_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Inspection Guid.
        /// </summary>
        public static string InspectionGuid_Invalid {
            get {
                return ResourceManager.GetString("InspectionGuid_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Id required.
        /// </summary>
        public static string InspectionId_Error_Required {
            get {
                return ResourceManager.GetString("InspectionId_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection cancelled successfully.
        /// </summary>
        public static string Inspections_Cancelled {
            get {
                return ResourceManager.GetString("Inspections_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Inspection Id.
        /// </summary>
        public static string Inspections_Error_InvalidId {
            get {
                return ResourceManager.GetString("Inspections_Error_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Image Id.
        /// </summary>
        public static string Inspections_Error_InvalidImageId {
            get {
                return ResourceManager.GetString("Inspections_Error_InvalidImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid inspection id / image id.
        /// </summary>
        public static string Inspections_Error_InvalidInspectionIdOrImageId {
            get {
                return ResourceManager.GetString("Inspections_Error_InvalidInspectionIdOrImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InspectionId cannot be zero.
        /// </summary>
        public static string Inspections_Error_ZeroInspectionId {
            get {
                return ResourceManager.GetString("Inspections_Error_ZeroInspectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lattitude and Longitude value is required.
        /// </summary>
        public static string Inspections_SaveImage_Error_EmptyLocation {
            get {
                return ResourceManager.GetString("Inspections_SaveImage_Error_EmptyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location is invalid. Please try again after sometime..
        /// </summary>
        public static string Inspections_SaveImage_Error_InvalidLocation {
            get {
                return ResourceManager.GetString("Inspections_SaveImage_Error_InvalidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Lender Configurations.
        /// </summary>
        public static string LenderConfigurations_Invalid {
            get {
                return ResourceManager.GetString("LenderConfigurations_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lender Configurations not found.
        /// </summary>
        public static string LenderConfigurations_NotFound {
            get {
                return ResourceManager.GetString("LenderConfigurations_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications not found.
        /// </summary>
        public static string Notifications_NotFound {
            get {
                return ResourceManager.GetString("Notifications_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot move the image as the inspection status is in {0}.
        /// </summary>
        public static string ReviewInspection_MoveImage_Error_CheckApplicationStatus {
            get {
                return ResourceManager.GetString("ReviewInspection_MoveImage_Error_CheckApplicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Image not found.
        /// </summary>
        public static string ReviewInspection_MoveImage_Error_DestinationImageNotFound {
            get {
                return ResourceManager.GetString("ReviewInspection_MoveImage_Error_DestinationImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Image Details.
        /// </summary>
        public static string ReviewInspection_MoveImage_Error_InvalidImageDetails {
            get {
                return ResourceManager.GetString("ReviewInspection_MoveImage_Error_InvalidImageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Image not found.
        /// </summary>
        public static string ReviewInspection_MoveImage_Error_SourceImageNotFound {
            get {
                return ResourceManager.GetString("ReviewInspection_MoveImage_Error_SourceImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Email not configured. Please contact Admin..
        /// </summary>
        public static string SendSubmissonReport_Error_ReportEmailNotConfigured {
            get {
                return ResourceManager.GetString("SendSubmissonReport_Error_ReportEmailNotConfigured", resourceCulture);
            }
        }
    }
}
