//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MobileWebAppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobileWebAppMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Messages.MobileWebAppMessages", typeof(MobileWebAppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Inspection Id or Image Id.
        /// </summary>
        public static string WebApp_GetImage_Error_InvalidImage {
            get {
                return ResourceManager.GetString("WebApp_GetImage_Error_InvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection ID mismatch, please try again.
        /// </summary>
        public static string WebApp_GetLenderLogo_Error_Inspection_Mismatch {
            get {
                return ResourceManager.GetString("WebApp_GetLenderLogo_Error_Inspection_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lender mismatch . please try again..
        /// </summary>
        public static string WebApp_GetLenderLogo_Error_Lender_Mismatch {
            get {
                return ResourceManager.GetString("WebApp_GetLenderLogo_Error_Lender_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lender company details not found.
        /// </summary>
        public static string WebApp_GetLenderLogo_Lender_Company_NotFound {
            get {
                return ResourceManager.GetString("WebApp_GetLenderLogo_Lender_Company_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        public static string WebApp_GetLenderLogo_UserNotFound {
            get {
                return ResourceManager.GetString("WebApp_GetLenderLogo_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Details not found.
        /// </summary>
        public static string WebApp_InspectionDetails_NotFound {
            get {
                return ResourceManager.GetString("WebApp_InspectionDetails_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lattitude and Longitude value is required.
        /// </summary>
        public static string WebApp_Inspections_SaveImage_Error_EmptyLocation {
            get {
                return ResourceManager.GetString("WebApp_Inspections_SaveImage_Error_EmptyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location is invalid. Please try again after sometime..
        /// </summary>
        public static string WebApp_Inspections_SaveImage_Error_InvalidLocation {
            get {
                return ResourceManager.GetString("WebApp_Inspections_SaveImage_Error_InvalidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string WebApp_Login_Error_IncorrectInspectionIdOrEmail {
            get {
                return ResourceManager.GetString("WebApp_Login_Error_IncorrectInspectionIdOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection ID not found.
        /// </summary>
        public static string WebApp_Login_Error_InvalidInpsection {
            get {
                return ResourceManager.GetString("WebApp_Login_Error_InvalidInpsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The One Time Pin entered is expired. Please try again.
        /// </summary>
        public static string WebApp_Login_Error_OTPExpired {
            get {
                return ResourceManager.GetString("WebApp_Login_Error_OTPExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The One Time Pin  you entered is invalid. Please enter the correct One Time Pin.
        /// </summary>
        public static string WebApp_Login_Error_VerifyOTP {
            get {
                return ResourceManager.GetString("WebApp_Login_Error_VerifyOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lender logo not found.
        /// </summary>
        public static string WebApp_Login_LenderLogo_NotFound {
            get {
                return ResourceManager.GetString("WebApp_Login_LenderLogo_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection ID mismatch, please try again.
        /// </summary>
        public static string WebApp_Processlist_Error_InvalidApplcationOrEmail {
            get {
                return ResourceManager.GetString("WebApp_Processlist_Error_InvalidApplcationOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your inspection cannot be processed. The lender selected accepts only private owners..
        /// </summary>
        public static string WebApp_Processlist_Error_NonOwnerNotAllowedMessage {
            get {
                return ResourceManager.GetString("WebApp_Processlist_Error_NonOwnerNotAllowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The One Time Pin already sent to your email or  mobile number. Please verify..
        /// </summary>
        public static string WebApp_ResendOTP_Error {
            get {
                return ResourceManager.GetString("WebApp_ResendOTP_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid inspection id / image id.
        /// </summary>
        public static string WebApp_SaveImages_EditInspection_InspectionProgress_Error_InvalidInspectionIdOrImageId {
            get {
                return ResourceManager.GetString("WebApp_SaveImages_EditInspection_InspectionProgress_Error_InvalidInspectionIdOrIm" +
                        "ageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No inspections are associated with this email or phone number.
        /// </summary>
        public static string WebApp_SendOpenInspection_Error_NoInspectionEmail {
            get {
                return ResourceManager.GetString("WebApp_SendOpenInspection_Error_NoInspectionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found.
        /// </summary>
        public static string WebApp_SubmitInspection_Error_Image_Not_Found {
            get {
                return ResourceManager.GetString("WebApp_SubmitInspection_Error_Image_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection not completed, please check the process list screen.
        /// </summary>
        public static string WebApp_SubmitInspection_Error_ProcesslistNotCompleted {
            get {
                return ResourceManager.GetString("WebApp_SubmitInspection_Error_ProcesslistNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection details are saved successfully.
        /// </summary>
        public static string WebApp_SubmitInspection_Success_SaveandExit {
            get {
                return ResourceManager.GetString("WebApp_SubmitInspection_Success_SaveandExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Submitted Successfully.
        /// </summary>
        public static string WebApp_SubmitInspection_Sucess_Inspection_Submission {
            get {
                return ResourceManager.GetString("WebApp_SubmitInspection_Sucess_Inspection_Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Make.
        /// </summary>
        public static string WebApp_UpdateDocumentStatus__InvalidMake {
            get {
                return ResourceManager.GetString("WebApp_UpdateDocumentStatus _InvalidMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Model.
        /// </summary>
        public static string WebApp_UpdateDocumentStatus__InvalidModel {
            get {
                return ResourceManager.GetString("WebApp_UpdateDocumentStatus _InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Driving Licence photo is not matched with selfie. please click Retry to capture Driving Licence again or Click Submit to upload..
        /// </summary>
        public static string WebApp_UpdatedocumentStatus_Error_DL_ForceUpload {
            get {
                return ResourceManager.GetString("WebApp_UpdatedocumentStatus_Error_DL_ForceUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Driving Licence photo is not matched with selfie.  please click Retry to capture Driving Licence again..
        /// </summary>
        public static string WebApp_UpdatedocumentStatus_Error_DL_Retry {
            get {
                return ResourceManager.GetString("WebApp_UpdatedocumentStatus_Error_DL_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please , upload all images of {0} to continue.
        /// </summary>
        public static string WebApp_UpdateDocumentStatus_Error_ImageNotUploaded {
            get {
                return ResourceManager.GetString("WebApp_UpdateDocumentStatus_Error_ImageNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Custom Relation.
        /// </summary>
        public static string WebApp_UpdatedocumentStatus_Error_Invalid_Custom_Relation {
            get {
                return ResourceManager.GetString("WebApp_UpdatedocumentStatus_Error_Invalid_Custom_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found.
        /// </summary>
        public static string WebApp_UpdateMotorDatas_Error_Image_Not_Found {
            get {
                return ResourceManager.GetString("WebApp_UpdateMotorDatas_Error_Image_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor details are successfully updated..
        /// </summary>
        public static string WebApp_UpdateMotorDatas_Success {
            get {
                return ResourceManager.GetString("WebApp_UpdateMotorDatas_Success", resourceCulture);
            }
        }
    }
}
