//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Messages.NotificationMessages", typeof(NotificationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, {1} wants to buy your {2}. Their lender {3} requires a Verimoto Inspection. Please click: {4} to proceed (Your inspection ID {5})..
        /// </summary>
        public static string InspectionCreationSMSWithBuyer {
            get {
                return ResourceManager.GetString("InspectionCreationSMSWithBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, in order for the buyer of your {1} to receive financing approval, their lender {2} requires a Verimoto Inspection Report. Please click: {3} to proceed (Your inspection ID {4})..
        /// </summary>
        public static string InspectionCreationSMSWithoutBuyer {
            get {
                return ResourceManager.GetString("InspectionCreationSMSWithoutBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which state is your vehicle registered?.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations for completing your Verimoto inspection! We’re working with {0} to help you finalize the sale of your {3}. If you have any questions, please call {1} on {2}..
        /// </summary>
        public static string SellerWhenAdminSubmits {
            get {
                return ResourceManager.GetString("SellerWhenAdminSubmits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using Verimoto! We are reviewing your information and will get back to you within the next working day. For assistance, please contact {0} at {1}.
        /// </summary>
        public static string SellerWhenSellerSubmitsTheApp {
            get {
                return ResourceManager.GetString("SellerWhenSellerSubmitsTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, here is Verimoto assistant. Your One Time Pin is {1}.
        /// </summary>
        public static string SendLogInOTP {
            get {
                return ResourceManager.GetString("SendLogInOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, open inspection id for your email / mobile - {1}.
        /// </summary>
        public static string SendOpenInspectionIds {
            get {
                return ResourceManager.GetString("SendOpenInspectionIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, unfortunately there was an issue with one or more of the documents you submitted and the Inspection cannot be completed. Please log in to Verimoto {1} to see details and provide replacements..
        /// </summary>
        public static string WebAppInspectionRejectionSMS {
            get {
                return ResourceManager.GetString("WebAppInspectionRejectionSMS", resourceCulture);
            }
        }
    }
}
