//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Messages.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already activated.
        /// </summary>
        public static string BrokerInvite_Error_EmailAlreadyActivated {
            get {
                return ResourceManager.GetString("BrokerInvite_Error_EmailAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not exist.
        /// </summary>
        public static string BrokerInvite_Error_InvalidEmailVerificationLink {
            get {
                return ResourceManager.GetString("BrokerInvite_Error_InvalidEmailVerificationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrokerUsers List required.
        /// </summary>
        public static string BrokerUsersList_Error_Required {
            get {
                return ResourceManager.GetString("BrokerUsersList_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company entered already exists.
        /// </summary>
        public static string CompanyDetails_Error_CompanyNameExists {
            get {
                return ResourceManager.GetString("CompanyDetails_Error_CompanyNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details not found.
        /// </summary>
        public static string CompanyDetails_Error_NotFound {
            get {
                return ResourceManager.GetString("CompanyDetails_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyGuid is required.
        /// </summary>
        public static string CompanyGuid_Error_Required {
            get {
                return ResourceManager.GetString("CompanyGuid_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not mapped.
        /// </summary>
        public static string CompanyNotMapped_Error {
            get {
                return ResourceManager.GetString("CompanyNotMapped_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultBrokerDetails reuired.
        /// </summary>
        public static string DeafultBrokerDetails_Error_Required {
            get {
                return ResourceManager.GetString("DeafultBrokerDetails_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Email Invalid.
        /// </summary>
        public static string DefaultEmail_Invalid {
            get {
                return ResourceManager.GetString("DefaultEmail_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lender name entered already exists.
        /// </summary>
        public static string Lender_Error_LenderNameExists {
            get {
                return ResourceManager.GetString("Lender_Error_LenderNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenders not found.
        /// </summary>
        public static string LendersList_NotFound {
            get {
                return ResourceManager.GetString("LendersList_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LenderUsers List Required.
        /// </summary>
        public static string LenderUsersList_Error_Required {
            get {
                return ResourceManager.GetString("LenderUsersList_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles not assigned for loggedin user.
        /// </summary>
        public static string LoggedinUser_Error_RolesNotAssigned {
            get {
                return ResourceManager.GetString("LoggedinUser_Error_RolesNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked. Please unlock your account and try again.
        /// </summary>
        public static string Login_Error_AccountLocked {
            get {
                return ResourceManager.GetString("Login_Error_AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate your email to continue. Activation link sent to your registered email..
        /// </summary>
        public static string Login_Error_AccountNotActivated {
            get {
                return ResourceManager.GetString("Login_Error_AccountNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not associated with any company. Please contact your admin..
        /// </summary>
        public static string Login_Error_CompanyNotAssociated {
            get {
                return ResourceManager.GetString("Login_Error_CompanyNotAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not mapped. Please contact your admin.
        /// </summary>
        public static string Login_Error_CompanyNotMapped {
            get {
                return ResourceManager.GetString("Login_Error_CompanyNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not registered. Please sign up.
        /// </summary>
        public static string Login_Error_EmailNotRegistered {
            get {
                return ResourceManager.GetString("Login_Error_EmailNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or password is incorrect.
        /// </summary>
        public static string Login_Error_IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("Login_Error_IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP you entered is invalid. Please enter the correct OTP.
        /// </summary>
        public static string Login_Verify_OTP {
            get {
                return ResourceManager.GetString("Login_Verify_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification successful! Please login to complete your profile.
        /// </summary>
        public static string Register_EmailSuccessfullyVerified {
            get {
                return ResourceManager.GetString("Register_EmailSuccessfullyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already activated.
        /// </summary>
        public static string Register_Error_EmailAlreadyActivated {
            get {
                return ResourceManager.GetString("Register_Error_EmailAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already activated. Login with your email and password..
        /// </summary>
        public static string Register_Error_EmailVerified {
            get {
                return ResourceManager.GetString("Register_Error_EmailVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid link. Please try again with valid link.
        /// </summary>
        public static string Register_Error_InvalidEmailVerificationLink {
            get {
                return ResourceManager.GetString("Register_Error_InvalidEmailVerificationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your link is revoked by the broker. Please contact your broker..
        /// </summary>
        public static string Register_Error_LinkRevoked {
            get {
                return ResourceManager.GetString("Register_Error_LinkRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again after 30 seconds..
        /// </summary>
        public static string Register_Error_ValidateResetPasswordLinkGeneratedTime {
            get {
                return ResourceManager.GetString("Register_Error_ValidateResetPasswordLinkGeneratedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists. Please login with your credentials.
        /// </summary>
        public static string Registration_Error_EmailExists {
            get {
                return ResourceManager.GetString("Registration_Error_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is incorrect.
        /// </summary>
        public static string Registration_Error_EmailNotExists {
            get {
                return ResourceManager.GetString("Registration_Error_EmailNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again after 30 seconds..
        /// </summary>
        public static string Registration_Error_MailAlreadySent {
            get {
                return ResourceManager.GetString("Registration_Error_MailAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email. Please contact your admin.
        /// </summary>
        public static string Registration_InvitedUser_Error_EmailNotExists {
            get {
                return ResourceManager.GetString("Registration_InvitedUser_Error_EmailNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already signedup with the email ({0})..
        /// </summary>
        public static string Registration_SignUp_PasswordAlreadyAssigned {
            get {
                return ResourceManager.GetString("Registration_SignUp_PasswordAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email registered successfully..
        /// </summary>
        public static string Registration_Success {
            get {
                return ResourceManager.GetString("Registration_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid e-mail address.Please try again..
        /// </summary>
        public static string ReserPassword_Error_InvalidEmail {
            get {
                return ResourceManager.GetString("ReserPassword_Error_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID entered is not registered with verimoto.
        /// </summary>
        public static string ResetPassword_Error_EmailNotRegistered {
            get {
                return ResourceManager.GetString("ResetPassword_Error_EmailNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid link.
        /// </summary>
        public static string ResetPassword_Error_InvalidLink {
            get {
                return ResourceManager.GetString("ResetPassword_Error_InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use same password. Please try again with different password..
        /// </summary>
        public static string ResetPassword_Error_UserOldCredential {
            get {
                return ResourceManager.GetString("ResetPassword_Error_UserOldCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists. Please try again with different email.
        /// </summary>
        public static string SaveUserProfile_Error_EmailExists {
            get {
                return ResourceManager.GetString("SaveUserProfile_Error_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        public static string SaveUserProfile_Error_InvalidUser {
            get {
                return ResourceManager.GetString("SaveUserProfile_Error_InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password required.
        /// </summary>
        public static string SaveUserProfile_Error_NewPasswordRequired {
            get {
                return ResourceManager.GetString("SaveUserProfile_Error_NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password not match.
        /// </summary>
        public static string SaveUserProfile_Error_OldPasswordNotMatch {
            get {
                return ResourceManager.GetString("SaveUserProfile_Error_OldPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password required.
        /// </summary>
        public static string SaveUserProfile_Error_OldPasswordRequired {
            get {
                return ResourceManager.GetString("SaveUserProfile_Error_OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldPassword and NewPassword cannot be same.
        /// </summary>
        public static string SaveUserProfile_Error_PasswordNotMatch {
            get {
                return ResourceManager.GetString("SaveUserProfile_Error_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportTeam Users not found.
        /// </summary>
        public static string SupportTeamUsers_NotFound {
            get {
                return ResourceManager.GetString("SupportTeamUsers_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportTeamUsers List required.
        /// </summary>
        public static string SupportTeamUsersList_Error_Required {
            get {
                return ResourceManager.GetString("SupportTeamUsersList_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        public static string User_Invalid {
            get {
                return ResourceManager.GetString("User_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGuid Required.
        /// </summary>
        public static string UserGuid_Required {
            get {
                return ResourceManager.GetString("UserGuid_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users not found.
        /// </summary>
        public static string Users_NotFound {
            get {
                return ResourceManager.GetString("Users_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Email should be present in users list.
        /// </summary>
        public static string ValidateUser_Error_DefaultEmailExist {
            get {
                return ResourceManager.GetString("ValidateUser_Error_DefaultEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Email is already registered as {0}. Please try again with different email..
        /// </summary>
        public static string ValidateUserEmail_Error_EmailExists {
            get {
                return ResourceManager.GetString("ValidateUserEmail_Error_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP expired. Please try agin with new otp.
        /// </summary>
        public static string VerifyOTP_Error_OTPExpired {
            get {
                return ResourceManager.GetString("VerifyOTP_Error_OTPExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login with password and then request for OTP.
        /// </summary>
        public static string VerifyOTP_Error_Relogin {
            get {
                return ResourceManager.GetString("VerifyOTP_Error_Relogin", resourceCulture);
            }
        }
    }
}
